### ISSUE TITLE
This song fits well for RIAA

### ISSUE THREAD

**Issue by GhbSmwc** [Zipdox/youtube-dl-reup#1]
https://www.youtube.com/watch?v=inGFn7abd54

**Comment by GhbSmwc** [comment]
And also, fuck 1201. That diarrhea is what allowed corporations to enforce restriction that is normally what copyright itself cannot do.

**Comment by GhbSmwc** [comment]
░░░░░░░░░░░█▀▀░░█░░░░░░ ░░░░░░▄▀▀▀▀░░░░░█▄▄░░░░ ░░░░░░█░█░░░░░░░░░░▐░░░ ░░░░░░▐▐░░░░░░░░░▄░▐░░░ ░░░░░░█░░░░░░░░▄▀▀░▐░░░ ░░░░▄▀░░░░░░░░▐░▄▄▀░░░░ ░░▄▀░░░▐░░░░░█▄▀░▐░░░░░ ░░█░░░▐░░░░░░░░▄░█░░░░░ ░░░█▄░░▀▄░░░░▄▀▐░█░░░░░ ░░░█▐▀▀▀░▀▀▀▀░░▐░█░░░░░ ░░▐█▐▄░░▀░░░░░░▐░█▄▄░░ ░░░▀▀░▄TSM▄░░░▐▄▄▄▀░░░

**Comment by Zipdox** [comment]
based
